### ISSUE TITLE
为什么node server的时候报端口错？

### ISSUE THREAD

**Issue by mngogo** [jrainlau/draw-something#12]
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8090
    at Object.exports._errnoException (util.js:1033:11)

kill 进程也没解决。 是哪里还需要安装或设置？

**Comment by NancyZY** [comment]
错误已经说明你的端口被占用了，你换个端口或者把占用该端口的程序关掉，应该就没问题了
