### ISSUE TITLE
Can't draw anything

### ISSUE THREAD

**Issue by zhangbowei** [jrainlau/draw-something#2]
when I  open draw tab and guess tab, I could not draw anything on red tab that is supposed to be drawn.

**Comment by zhangbowei** [comment]
Version 51.0.2704.103 (64-bit)

**Comment by zhangbowei** [comment]
chrome Version 51.0.2704.103 (64-bit) 
OS X 10.10.5

**Comment by jrainlau** [comment]
Have you started the WebSocket server? Before `npm run dev`, you should `node ws-server.js` first.
