### ISSUE TITLE
npm error after 'npm install'

### ISSUE THREAD

**Issue by jmx164491960** [jrainlau/draw-something#4]
npm报错，然后输入node ws-server也没反应了。请问怎么解决？是因为npm版本不对？

D:\Demo\77\draw-something>npm install
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead
 of autoprefixer-loader
npm WARN peerDependencies The peer dependency vue-hot-reload-api@^1.2.0 included
 from vue-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.12
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package vue-hot-reload-api@2.0.5 does not satisfy its s
iblings' peerDependencies requirements!
npm ERR! peerinvalid Peer vue-loader@8.5.3 wants vue-hot-reload-api@^1.2.0

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Demo\77\draw-something\npm-debug.log

D:\Demo\77\draw-something>node ws-server.js

**Comment by jrainlau** [comment]
目测是npm的问题，你试试升级一下

**Comment by lin30** [comment]
我的npm是3.10.0 npm ws-server.js  也是没反应，控制台也不报错

**Comment by jrainlau** [comment]
开发环境的npm版本是3.3.12，在这之后的版本应该都能正确运行npm install。如果还持续报错，可以尝试使用cnpm。
另外运行ws-server.js请使用node而非npm
