### ISSUE TITLE
运行node ws-server.js提示Use of const in strict mode

### ISSUE THREAD

**Issue by FrontEndRoad** [jrainlau/draw-something#5]
node ws-server.js // 开启websocket服务器
E:\learn\websocket\draw-something\node ws-server.js

E:\learn\websocket\draw-something\ws-server.js
const WebSocketServer = require('ws').Server

SyntaxError: Use of const in strict mode.

JS中添加的有‘use strict’，运行一直报以上错误，请问是怎么回事呢？

**Comment by jrainlau** [comment]
可能是你的node版本比较旧，可以尝试更新node版本重新尝试
