### ISSUE TITLE
Vue.config._lifecycleHooks is undefined

### ISSUE THREAD

**Issue by yayifei2426** [jrainlau/draw-something#7]
Uncaught TypeError: Cannot read property 'indexOf' of undefinedexports.install @ index.js?2c45:15
即：Vue.config._lifecycleHooks is undefined
请问这个报错是什么意思啊？

**Comment by jrainlau** [comment]
在运行到哪一步的时候出现的？位置在哪？

**Comment by yayifei2426** [comment]
就是浏览器刚开始运行console里的报错

**Comment by congtou221** [comment]
我也遇到了这个问题

**Comment by jrainlau** [comment]
请使用v50或以上的chrome浏览器测试。
同时由于package.json里面的依赖包年代久远，npm install无法完全下载所有的依赖包，我已经在最近的commit里面把整个node_modules文件夹上传了，所以可以省略npm install这一步，直接开启ws服务器以及npm run dev即可。
