### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Lunaticf** [jrainlau/draw-something#8]
从你的mottojs看到你的github，感觉有好多好玩的东西 而且各种框架库新技术都用的很不错...自己现在就学的很迷茫...新手..能不能推荐一些学习资源和方法呀...感激不尽 
ps:不知道这里提这些是否恰当

**Comment by jrainlau** [comment]
哈哈，感谢你的支持！其实你可以通过email联系我：jrainlau@163.com；也可以在segmentfault社区给我留言：@Jrainlau
新手的话，先把[http://www.imooc.com/](http://www.imooc.com/) 的前端基础课程通通过一遍，然后自己写一些小的项目。可以先从简单的模仿静态页面开始，渐渐地加入JS，实现一些简单的诸如轮播图之类的交互。同时看看《高程3》之类的经典书籍。
以我的经验来看，找一份实习是很重要的，在实习的过程中你会遇到各种各样的问题，正是这些问题以及解决问题的能力不断促使着你的进步。
加油啦，有什么问题随时与我联系~

**Comment by Lunaticf** [comment]
非常感谢你的热情回复 我会加油的！

发自我的 iPad
